From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_person__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_moss__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_sage__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__ancestor____of__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_person__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_moss__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_sage__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__ancestor____of__iso.

  Export Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_person__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_moss__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_sage__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__ancestor____of__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_person__iso.Interface <+ Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_moss__iso.Interface <+ Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__U_sage__iso.Interface <+ Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__ancestor____of__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex : imported_Original_LF__DOT__IndProp_LF_IndProp_ancestor__of imported_Original_LF__DOT__IndProp_LF_IndProp_Sage imported_Original_LF__DOT__IndProp_LF_IndProp_Moss.
Parameter Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex_iso : rel_iso (Original_LF__DOT__IndProp_LF_IndProp_ancestor__of_iso Original_LF__DOT__IndProp_LF_IndProp_Sage_iso Original_LF__DOT__IndProp_LF_IndProp_Moss_iso)
    Original.LF_DOT_IndProp.LF.IndProp.ancestor_of_ex imported_Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex.
Existing Instance Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_IndProp.LF.IndProp.ancestor_of_ex ?x) => unify x Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_IndProp.LF.IndProp.ancestor_of_ex imported_Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex ?x) => unify x Original_LF__DOT__IndProp_LF_IndProp_ancestor__of__ex_iso; constructor : typeclass_instances.


End Interface.