From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__bexp__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus____b__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.bool__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__beval__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__bexp__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus____b__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.bool__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__beval__iso.

  Export Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__bexp__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus____b__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks Interface.bool__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__beval__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__bexp__iso.Interface <+ Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus____b__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface <+ Interface.bool__iso.Interface <+ Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__beval__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound : forall x : imported_Original_LF__DOT__Imp_LF_Imp_AExp_bexp,
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Imp_LF_Imp_AExp_beval (imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b x))
    (imported_Original_LF__DOT__Imp_LF_Imp_AExp_beval x).
Parameter Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound_iso : forall (x1 : Original.LF_DOT_Imp.LF.Imp.AExp.bexp) (x2 : imported_Original_LF__DOT__Imp_LF_Imp_AExp_bexp) (hx : rel_iso Original_LF__DOT__Imp_LF_Imp_AExp_bexp_iso x1 x2),
  rel_iso (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Imp_LF_Imp_AExp_beval_iso (Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b_iso hx)) (Original_LF__DOT__Imp_LF_Imp_AExp_beval_iso hx))
    (Original.LF_DOT_Imp.LF.Imp.AExp.optimize_0plus_b_sound x1) (imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound x2).
Existing Instance Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Imp.LF.Imp.AExp.optimize_0plus_b_sound ?x) => unify x Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Imp.LF.Imp.AExp.optimize_0plus_b_sound imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound ?x) => unify x Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__b__sound_iso; constructor : typeclass_instances.


End Interface.