From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__day__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__next____working____day__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__saturday__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__tuesday__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__day__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__next____working____day__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__saturday__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__tuesday__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__day__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__next____working____day__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__saturday__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__tuesday__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__day__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__next____working____day__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__saturday__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__tuesday__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_test__next__working__day : imported_Corelib_Init_Logic_eq
    (imported_Original_LF__DOT__Basics_LF_Basics_next__working__day (imported_Original_LF__DOT__Basics_LF_Basics_next__working__day imported_Original_LF__DOT__Basics_LF_Basics_saturday))
    imported_Original_LF__DOT__Basics_LF_Basics_tuesday.
Parameter Original_LF__DOT__Basics_LF_Basics_test__next__working__day_iso : rel_iso
    (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Basics_LF_Basics_next__working__day_iso (Original_LF__DOT__Basics_LF_Basics_next__working__day_iso Original_LF__DOT__Basics_LF_Basics_saturday_iso))
       Original_LF__DOT__Basics_LF_Basics_tuesday_iso)
    Original.LF_DOT_Basics.LF.Basics.test_next_working_day imported_Original_LF__DOT__Basics_LF_Basics_test__next__working__day.
Existing Instance Original_LF__DOT__Basics_LF_Basics_test__next__working__day_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.test_next_working_day ?x) => unify x Original_LF__DOT__Basics_LF_Basics_test__next__working__day_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.test_next_working_day imported_Original_LF__DOT__Basics_LF_Basics_test__next__working__day ?x) => unify x Original_LF__DOT__Basics_LF_Basics_test__next__working__day_iso; constructor : typeclass_instances.


End Interface.