From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade____comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_plus__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade____comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_plus__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade____comparison__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_plus__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade____comparison__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_plus__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3 : imported_Corelib_Init_Logic_eq
    (imported_Original_LF__DOT__Basics_LF_Basics_grade__comparison
       (imported_Original_LF__DOT__Basics_LF_Basics_Grade imported_Original_LF__DOT__Basics_LF_Basics_F imported_Original_LF__DOT__Basics_LF_Basics_Plus)
       (imported_Original_LF__DOT__Basics_LF_Basics_Grade imported_Original_LF__DOT__Basics_LF_Basics_F imported_Original_LF__DOT__Basics_LF_Basics_Plus))
    imported_Original_LF__DOT__Basics_LF_Basics_Eq.
Parameter Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3_iso : rel_iso
    (Corelib_Init_Logic_eq_iso
       (Original_LF__DOT__Basics_LF_Basics_grade__comparison_iso (Original_LF__DOT__Basics_LF_Basics_Grade_iso Original_LF__DOT__Basics_LF_Basics_F_iso Original_LF__DOT__Basics_LF_Basics_Plus_iso)
          (Original_LF__DOT__Basics_LF_Basics_Grade_iso Original_LF__DOT__Basics_LF_Basics_F_iso Original_LF__DOT__Basics_LF_Basics_Plus_iso))
       Original_LF__DOT__Basics_LF_Basics_Eq_iso)
    Original.LF_DOT_Basics.LF.Basics.test_grade_comparison3 imported_Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3.
Existing Instance Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.test_grade_comparison3 ?x) => unify x Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.test_grade_comparison3 imported_Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3 ?x) => unify x Original_LF__DOT__Basics_LF_Basics_test__grade__comparison3_iso; constructor : typeclass_instances.


End Interface.