From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_lt__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____letter__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_lt__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____letter__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_lt__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____letter__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_lt__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_f__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____letter__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers : forall x : imported_Original_LF__DOT__Basics_LF_Basics_letter,
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison imported_Original_LF__DOT__Basics_LF_Basics_F x) imported_Original_LF__DOT__Basics_LF_Basics_Lt ->
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison (imported_Original_LF__DOT__Basics_LF_Basics_lower__letter x) x)
    imported_Original_LF__DOT__Basics_LF_Basics_Lt.
Parameter Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers_iso : forall (x1 : Original.LF_DOT_Basics.LF.Basics.letter) (x2 : imported_Original_LF__DOT__Basics_LF_Basics_letter) (hx : rel_iso Original_LF__DOT__Basics_LF_Basics_letter_iso x1 x2)
    (x3 : Original.LF_DOT_Basics.LF.Basics.letter_comparison Original.LF_DOT_Basics.LF.Basics.F x1 = Original.LF_DOT_Basics.LF.Basics.Lt)
    (x4 : imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison imported_Original_LF__DOT__Basics_LF_Basics_F x2)
            imported_Original_LF__DOT__Basics_LF_Basics_Lt),
  rel_iso (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Basics_LF_Basics_letter__comparison_iso Original_LF__DOT__Basics_LF_Basics_F_iso hx) Original_LF__DOT__Basics_LF_Basics_Lt_iso) x3 x4 ->
  rel_iso
    (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Basics_LF_Basics_letter__comparison_iso (Original_LF__DOT__Basics_LF_Basics_lower__letter_iso hx) hx) Original_LF__DOT__Basics_LF_Basics_Lt_iso)
    (Original.LF_DOT_Basics.LF.Basics.lower_letter_lowers x1 x3) (imported_Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers x4).
Existing Instance Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.lower_letter_lowers ?x) => unify x Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.lower_letter_lowers imported_Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers ?x) => unify x Original_LF__DOT__Basics_LF_Basics_lower__letter__lowers_iso; constructor : typeclass_instances.


End Interface.