From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__t____tree__iso Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__reflect__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__t____tree__iso Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__reflect__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__t____tree__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__reflect__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__t____tree__iso.Interface <+ Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__reflect__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution : forall (x : Type) (x0 : imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_t__tree x),
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect (imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect x0)) x0.
Parameter Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution_iso : forall (x1 x2 : Type) (hx : Iso x1 x2) (x3 : Original.LF_DOT_IndPrinciples.LF.IndPrinciples.t_tree x1) (x4 : imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_t__tree x2)
    (hx0 : rel_iso (Original_LF__DOT__IndPrinciples_LF_IndPrinciples_t__tree_iso hx) x3 x4),
  rel_iso (Corelib_Init_Logic_eq_iso (Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect_iso (Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect_iso hx0)) hx0)
    (Original.LF_DOT_IndPrinciples.LF.IndPrinciples.reflect_involution x1 x3) (imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution x4).
Existing Instance Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_IndPrinciples.LF.IndPrinciples.reflect_involution ?x) => unify x Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_IndPrinciples.LF.IndPrinciples.reflect_involution imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution ?x) => unify x Original_LF__DOT__IndPrinciples_LF_IndPrinciples_reflect__involution_iso; constructor : typeclass_instances.


End Interface.