From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__id__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__partial____map__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__find__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__U_some__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__update__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__id__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__partial____map__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__find__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__U_some__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__update__iso.

  Export Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__id__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__partial____map__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__find__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks Interface.nat__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__U_some__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__update__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__id__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__partial____map__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__find__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface <+ Interface.nat__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__U_some__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__update__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Lists_LF_Lists_update__eq : forall (x : imported_Original_LF__DOT__Lists_LF_Lists_partial__map) (x0 : imported_Original_LF__DOT__Lists_LF_Lists_id) (x1 : imported_nat),
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Lists_LF_Lists_find x0 (imported_Original_LF__DOT__Lists_LF_Lists_update x x0 x1))
    (imported_Original_LF__DOT__Lists_LF_Lists_NatList_Some x1).
Parameter Original_LF__DOT__Lists_LF_Lists_update__eq_iso : forall (x1 : Original.LF_DOT_Lists.LF.Lists.partial_map) (x2 : imported_Original_LF__DOT__Lists_LF_Lists_partial__map) (hx : rel_iso Original_LF__DOT__Lists_LF_Lists_partial__map_iso x1 x2)
    (x3 : Original.LF_DOT_Lists.LF.Lists.id) (x4 : imported_Original_LF__DOT__Lists_LF_Lists_id) (hx0 : rel_iso Original_LF__DOT__Lists_LF_Lists_id_iso x3 x4) (x5 : nat) (x6 : imported_nat)
    (hx1 : rel_iso nat_iso x5 x6),
  rel_iso (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Lists_LF_Lists_find_iso hx0 (Original_LF__DOT__Lists_LF_Lists_update_iso hx hx0 hx1)) (Original_LF__DOT__Lists_LF_Lists_NatList_Some_iso hx1))
    (Original.LF_DOT_Lists.LF.Lists.update_eq x1 x3 x5) (imported_Original_LF__DOT__Lists_LF_Lists_update__eq x2 x4 x6).
Existing Instance Original_LF__DOT__Lists_LF_Lists_update__eq_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Lists.LF.Lists.update_eq ?x) => unify x Original_LF__DOT__Lists_LF_Lists_update__eq_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Lists.LF.Lists.update_eq imported_Original_LF__DOT__Lists_LF_Lists_update__eq ?x) => unify x Original_LF__DOT__Lists_LF_Lists_update__eq_iso; constructor : typeclass_instances.


End Interface.