From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_c__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_minus__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_natural__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_c__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_minus__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_natural__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_c__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____grade__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_minus__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_natural__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__grade__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_c__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__lower____grade__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__modifier__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_grade__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_minus__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_natural__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_lower__grade__twice : imported_Corelib_Init_Logic_eq
    (imported_Original_LF__DOT__Basics_LF_Basics_lower__grade
       (imported_Original_LF__DOT__Basics_LF_Basics_lower__grade
          (imported_Original_LF__DOT__Basics_LF_Basics_Grade imported_Original_LF__DOT__Basics_LF_Basics_B imported_Original_LF__DOT__Basics_LF_Basics_Minus)))
    (imported_Original_LF__DOT__Basics_LF_Basics_Grade imported_Original_LF__DOT__Basics_LF_Basics_C imported_Original_LF__DOT__Basics_LF_Basics_Natural).
Parameter Original_LF__DOT__Basics_LF_Basics_lower__grade__twice_iso : rel_iso
    (Corelib_Init_Logic_eq_iso
       (Original_LF__DOT__Basics_LF_Basics_lower__grade_iso
          (Original_LF__DOT__Basics_LF_Basics_lower__grade_iso (Original_LF__DOT__Basics_LF_Basics_Grade_iso Original_LF__DOT__Basics_LF_Basics_B_iso Original_LF__DOT__Basics_LF_Basics_Minus_iso)))
       (Original_LF__DOT__Basics_LF_Basics_Grade_iso Original_LF__DOT__Basics_LF_Basics_C_iso Original_LF__DOT__Basics_LF_Basics_Natural_iso))
    Original.LF_DOT_Basics.LF.Basics.lower_grade_twice imported_Original_LF__DOT__Basics_LF_Basics_lower__grade__twice.
Existing Instance Original_LF__DOT__Basics_LF_Basics_lower__grade__twice_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.lower_grade_twice ?x) => unify x Original_LF__DOT__Basics_LF_Basics_lower__grade__twice_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.lower_grade_twice imported_Original_LF__DOT__Basics_LF_Basics_lower__grade__twice ?x) => unify x Original_LF__DOT__Basics_LF_Basics_lower__grade__twice_iso; constructor : typeclass_instances.


End Interface.