From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__tl__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_nat__pred__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__length__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__tl__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_nat__pred__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__length__iso.

  Export Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__tl__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks Interface.nat__iso.CodeBlocks Interface.U_nat__pred__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__length__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__tl__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface <+ Interface.nat__iso.Interface <+ Interface.U_nat__pred__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__length__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred : forall x : imported_Original_LF__DOT__Lists_LF_Lists_NatList_natlist,
  imported_Corelib_Init_Logic_eq (imported_Nat_pred (imported_Original_LF__DOT__Lists_LF_Lists_NatList_length x))
    (imported_Original_LF__DOT__Lists_LF_Lists_NatList_length (imported_Original_LF__DOT__Lists_LF_Lists_NatList_tl x)).
Parameter Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred_iso : forall (x1 : Original.LF_DOT_Lists.LF.Lists.NatList.natlist) (x2 : imported_Original_LF__DOT__Lists_LF_Lists_NatList_natlist)
    (hx : rel_iso Original_LF__DOT__Lists_LF_Lists_NatList_natlist_iso x1 x2),
  rel_iso
    (Corelib_Init_Logic_eq_iso (Nat_pred_iso (Original_LF__DOT__Lists_LF_Lists_NatList_length_iso hx))
       (Original_LF__DOT__Lists_LF_Lists_NatList_length_iso (Original_LF__DOT__Lists_LF_Lists_NatList_tl_iso hx)))
    (Original.LF_DOT_Lists.LF.Lists.NatList.tl_length_pred x1) (imported_Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred x2).
Existing Instance Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Lists.LF.Lists.NatList.tl_length_pred ?x) => unify x Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Lists.LF.Lists.NatList.tl_length_pred imported_Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred ?x) => unify x Original_LF__DOT__Lists_LF_Lists_NatList_tl__length__pred_iso; constructor : typeclass_instances.


End Interface.