From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_ascii__ascii__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__string__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__option__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__prod__iso Interface.nat__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_ascii__ascii__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__string__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__option__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__prod__iso Interface.nat__iso.

  Export Interface.U_ascii__ascii__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__string__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__option__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__prod__iso.CodeBlocks Interface.nat__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_ascii__ascii__iso.Interface <+ Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso.Interface <+ Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__string__iso.Interface <+ Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__option__iso.Interface <+ Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__prod__iso.Interface <+ Interface.nat__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux : imported_Original_LF__DOT__Poly_LF_Poly_option (imported_Original_LF__DOT__Poly_LF_Poly_prod imported_nat (imported_Original_LF__DOT__Poly_LF_Poly_list imported_Ascii_ascii)).
Parameter Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux_iso : rel_iso (Original_LF__DOT__Poly_LF_Poly_option_iso (Original_LF__DOT__Poly_LF_Poly_prod_iso nat_iso (Original_LF__DOT__Poly_LF_Poly_list_iso Ascii_ascii_iso)))
    Original.LF_DOT_AltAuto.LF.AltAuto.manual_grade_for_pumping_redux imported_Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux.
Existing Instance Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_AltAuto.LF.AltAuto.manual_grade_for_pumping_redux ?x) => unify x Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_AltAuto.LF.AltAuto.manual_grade_for_pumping_redux imported_Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux ?x) => unify x Original_LF__DOT__AltAuto_LF_AltAuto_manual__grade__for__pumping__redux_iso; constructor : typeclass_instances.


End Interface.