From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd____error__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__option____elim__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd____error__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__option____elim__iso.

  Export Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd____error__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks Interface.nat__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__option____elim__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natlist__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natoption__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd____error__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface <+ Interface.nat__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__hd__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__option____elim__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd : forall (x : imported_Original_LF__DOT__Lists_LF_Lists_NatList_natlist) (x0 : imported_nat),
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Lists_LF_Lists_NatList_hd x0 x)
    (imported_Original_LF__DOT__Lists_LF_Lists_NatList_option__elim x0 (imported_Original_LF__DOT__Lists_LF_Lists_NatList_hd__error x)).
Parameter Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd_iso : forall (x1 : Original.LF_DOT_Lists.LF.Lists.NatList.natlist) (x2 : imported_Original_LF__DOT__Lists_LF_Lists_NatList_natlist)
    (hx : rel_iso Original_LF__DOT__Lists_LF_Lists_NatList_natlist_iso x1 x2) (x3 : nat) (x4 : imported_nat) (hx0 : rel_iso nat_iso x3 x4),
  rel_iso
    (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Lists_LF_Lists_NatList_hd_iso hx0 hx)
       (Original_LF__DOT__Lists_LF_Lists_NatList_option__elim_iso hx0 (Original_LF__DOT__Lists_LF_Lists_NatList_hd__error_iso hx)))
    (Original.LF_DOT_Lists.LF.Lists.NatList.option_elim_hd x1 x3) (imported_Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd x2 x4).
Existing Instance Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Lists.LF.Lists.NatList.option_elim_hd ?x) => unify x Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Lists.LF.Lists.NatList.option_elim_hd imported_Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd ?x) => unify x Original_LF__DOT__Lists_LF_Lists_NatList_option__elim__hd_iso; constructor : typeclass_instances.


End Interface.