From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aexp__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aeval__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aexp__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aeval__iso.

  Export Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aexp__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks Interface.nat__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aeval__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aexp__iso.Interface <+ Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__optimize____0plus__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface <+ Interface.nat__iso.Interface <+ Interface.U_original__U2_lf_dot_U_imp__U2_lf__U_imp__U2_aexp__aeval__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound' : forall x : imported_Original_LF__DOT__Imp_LF_Imp_AExp_aexp,
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Imp_LF_Imp_AExp_aeval (imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus x)) (imported_Original_LF__DOT__Imp_LF_Imp_AExp_aeval x).
Parameter Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound'_iso : forall (x1 : Original.LF_DOT_Imp.LF.Imp.AExp.aexp) (x2 : imported_Original_LF__DOT__Imp_LF_Imp_AExp_aexp) (hx : rel_iso Original_LF__DOT__Imp_LF_Imp_AExp_aexp_iso x1 x2),
  rel_iso (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Imp_LF_Imp_AExp_aeval_iso (Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus_iso hx)) (Original_LF__DOT__Imp_LF_Imp_AExp_aeval_iso hx))
    (Original.LF_DOT_Imp.LF.Imp.AExp.optimize_0plus_sound' x1) (imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound' x2).
Existing Instance Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound'_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Imp.LF.Imp.AExp.optimize_0plus_sound' ?x) => unify x Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound'_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Imp.LF.Imp.AExp.optimize_0plus_sound' imported_Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound' ?x) => unify x Original_LF__DOT__Imp_LF_Imp_AExp_optimize__0plus__sound'_iso; constructor : typeclass_instances.


End Interface.