From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natprod__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__swap____pair__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__fst__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__pair__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__snd__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natprod__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__swap____pair__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso Interface.nat__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__fst__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__pair__iso Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__snd__iso.

  Export Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natprod__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__swap____pair__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks Interface.nat__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__fst__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__pair__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__snd__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__natprod__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__swap____pair__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface <+ Interface.nat__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__fst__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__pair__iso.Interface <+ Interface.U_original__U2_lf_dot_U_lists__U2_lf__U_lists__U_natU_list__snd__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap : forall x : imported_Original_LF__DOT__Lists_LF_Lists_NatList_natprod,
  imported_Corelib_Init_Logic_eq
    (imported_Original_LF__DOT__Lists_LF_Lists_NatList_pair (imported_Original_LF__DOT__Lists_LF_Lists_NatList_snd x) (imported_Original_LF__DOT__Lists_LF_Lists_NatList_fst x))
    (imported_Original_LF__DOT__Lists_LF_Lists_NatList_swap__pair x).
Parameter Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap_iso : forall (x1 : Original.LF_DOT_Lists.LF.Lists.NatList.natprod) (x2 : imported_Original_LF__DOT__Lists_LF_Lists_NatList_natprod)
    (hx : rel_iso Original_LF__DOT__Lists_LF_Lists_NatList_natprod_iso x1 x2),
  rel_iso
    (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Lists_LF_Lists_NatList_pair_iso (Original_LF__DOT__Lists_LF_Lists_NatList_snd_iso hx) (Original_LF__DOT__Lists_LF_Lists_NatList_fst_iso hx))
       (Original_LF__DOT__Lists_LF_Lists_NatList_swap__pair_iso hx))
    (Original.LF_DOT_Lists.LF.Lists.NatList.snd_fst_is_swap x1) (imported_Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap x2).
Existing Instance Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Lists.LF.Lists.NatList.snd_fst_is_swap ?x) => unify x Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Lists.LF.Lists.NatList.snd_fst_is_swap imported_Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap ?x) => unify x Original_LF__DOT__Lists_LF_Lists_NatList_snd__fst__is__swap_iso; constructor : typeclass_instances.


End Interface.