From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__nostutter__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__nil__iso Interface.nat__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__nostutter__iso Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__nil__iso Interface.nat__iso.

  Export Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__nostutter__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__nil__iso.CodeBlocks Interface.nat__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__list__iso.Interface <+ Interface.U_original__U2_lf_dot_U_indU_prop__U2_lf__U_indU_prop__nostutter__iso.Interface <+ Interface.U_original__U2_lf_dot_U_poly__U2_lf__U_poly__nil__iso.Interface <+ Interface.nat__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2 : imported_Original_LF__DOT__IndProp_LF_IndProp_nostutter (imported_Original_LF__DOT__Poly_LF_Poly_nil imported_nat).
Parameter Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2_iso : rel_iso (Original_LF__DOT__IndProp_LF_IndProp_nostutter_iso (Original_LF__DOT__Poly_LF_Poly_nil_iso nat_iso)) Original.LF_DOT_IndProp.LF.IndProp.test_nostutter_2
    imported_Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2.
Existing Instance Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_IndProp.LF.IndProp.test_nostutter_2 ?x) => unify x Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_IndProp.LF.IndProp.test_nostutter_2 imported_Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2 ?x) => unify x Original_LF__DOT__IndProp_LF_IndProp_test__nostutter__2_iso; constructor : typeclass_instances.


End Interface.