From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__comparison__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_eq__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__letter____comparison__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq : forall x : imported_Original_LF__DOT__Basics_LF_Basics_letter,
  imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison x x) imported_Original_LF__DOT__Basics_LF_Basics_Eq.
Parameter Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq_iso : forall (x1 : Original.LF_DOT_Basics.LF.Basics.letter) (x2 : imported_Original_LF__DOT__Basics_LF_Basics_letter) (hx : rel_iso Original_LF__DOT__Basics_LF_Basics_letter_iso x1 x2),
  rel_iso (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Basics_LF_Basics_letter__comparison_iso hx hx) Original_LF__DOT__Basics_LF_Basics_Eq_iso)
    (Original.LF_DOT_Basics.LF.Basics.letter_comparison_Eq x1) (imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq x2).
Existing Instance Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.letter_comparison_Eq ?x) => unify x Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.letter_comparison_Eq imported_Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq ?x) => unify x Original_LF__DOT__Basics_LF_Basics_letter__comparison__Eq_iso; constructor : typeclass_instances.


End Interface.