From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__better____t____tree____ind____type__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__better____t____tree____ind____type__iso.

  Export Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__better____t____tree____ind____type__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__better____t____tree____ind____type__iso.Args <+ Interface.U_original__U2_lf_dot_U_indU_principles__U2_lf__U_indU_principles__better____t____tree____ind____type__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind : imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind__type.
Parameter Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind_iso : rel_iso Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind__type_iso Original.LF_DOT_IndPrinciples.LF.IndPrinciples.better_t_tree_ind
    imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind.
Existing Instance Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_IndPrinciples.LF.IndPrinciples.better_t_tree_ind ?x) => unify x Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_IndPrinciples.LF.IndPrinciples.better_t_tree_ind imported_Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind ?x) => unify x Original_LF__DOT__IndPrinciples_LF_IndPrinciples_better__t__tree__ind_iso; constructor : typeclass_instances.


End Interface.