From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bin__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b0__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b1__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_z__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__incr__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bin__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b0__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b1__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_z__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__incr__iso Interface.U_true__iso Interface.U_corelib__U_init__U_logic__eq__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bin__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b0__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b1__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_z__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__incr__iso.CodeBlocks Interface.U_true__iso.CodeBlocks Interface.U_corelib__U_init__U_logic__eq__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bin__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b0__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_b1__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_z__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__incr__iso.Interface <+ Interface.U_true__iso.Interface <+ Interface.U_corelib__U_init__U_logic__eq__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_test__bin__incr1 : imported_Corelib_Init_Logic_eq (imported_Original_LF__DOT__Basics_LF_Basics_incr (imported_Original_LF__DOT__Basics_LF_Basics_B1 imported_Original_LF__DOT__Basics_LF_Basics_Z))
    (imported_Original_LF__DOT__Basics_LF_Basics_B0 (imported_Original_LF__DOT__Basics_LF_Basics_B1 imported_Original_LF__DOT__Basics_LF_Basics_Z)).
Parameter Original_LF__DOT__Basics_LF_Basics_test__bin__incr1_iso : rel_iso
    (Corelib_Init_Logic_eq_iso (Original_LF__DOT__Basics_LF_Basics_incr_iso (Original_LF__DOT__Basics_LF_Basics_B1_iso Original_LF__DOT__Basics_LF_Basics_Z_iso))
       (Original_LF__DOT__Basics_LF_Basics_B0_iso (Original_LF__DOT__Basics_LF_Basics_B1_iso Original_LF__DOT__Basics_LF_Basics_Z_iso)))
    Original.LF_DOT_Basics.LF.Basics.test_bin_incr1 imported_Original_LF__DOT__Basics_LF_Basics_test__bin__incr1.
Existing Instance Original_LF__DOT__Basics_LF_Basics_test__bin__incr1_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.test_bin_incr1 ?x) => unify x Original_LF__DOT__Basics_LF_Basics_test__bin__incr1_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.test_bin_incr1 imported_Original_LF__DOT__Basics_LF_Basics_test__bin__incr1 ?x) => unify x Original_LF__DOT__Basics_LF_Basics_test__bin__incr1_iso; constructor : typeclass_instances.


End Interface.