From Stdlib Require Import Derive.
From IsomorphismChecker Require Import IsomorphismStatementAutomationDefinitions EqualityLemmas IsomorphismDefinitions.
Import IsomorphismChecker.EqualityLemmas.IsoEq.
#[local] Unset Universe Polymorphism.
#[local] Set Implicit Arguments.
#[local] Hint Constants Opaque : typeclass_instances.
From IsomorphismChecker Require Original.

From IsomorphismChecker Require Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_tupleU_playground__nybble__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bool__iso.

Module Export CodeBlocks.

  Export (hints) Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_tupleU_playground__nybble__iso Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bool__iso.

  Export Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_tupleU_playground__nybble__iso.CodeBlocks Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bool__iso.CodeBlocks.

End CodeBlocks.

Module Type Args := Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__U_tupleU_playground__nybble__iso.Interface <+ Interface.U_original__U2_lf_dot_U_basics__U2_lf__U_basics__bool__iso.Interface.

Module Type Interface (Import args : Args).

Parameter imported_Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero : imported_Original_LF__DOT__Basics_LF_Basics_TuplePlayground_nybble -> imported_Original_LF__DOT__Basics_LF_Basics_bool.
Parameter Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero_iso : forall (x1 : Original.LF_DOT_Basics.LF.Basics.TuplePlayground.nybble) (x2 : imported_Original_LF__DOT__Basics_LF_Basics_TuplePlayground_nybble),
  rel_iso Original_LF__DOT__Basics_LF_Basics_TuplePlayground_nybble_iso x1 x2 ->
  rel_iso Original_LF__DOT__Basics_LF_Basics_bool_iso (Original.LF_DOT_Basics.LF.Basics.TuplePlayground.all_zero x1) (imported_Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero x2).
Existing Instance Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero_iso.
#[export] Hint Extern 0 (IsoStatementProofFor Original.LF_DOT_Basics.LF.Basics.TuplePlayground.all_zero ?x) => unify x Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero_iso; constructor : typeclass_instances.
#[export] Hint Extern 0 (IsoStatementProofBetween Original.LF_DOT_Basics.LF.Basics.TuplePlayground.all_zero imported_Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero ?x) => unify x Original_LF__DOT__Basics_LF_Basics_TuplePlayground_all__zero_iso; constructor : typeclass_instances.


End Interface.